#!/usr/bin/env python3
"""Generate perfect mazes as TikZ/LaTeX and compile to PDF.

Each maze is a spanning tree of an m×n grid graph, generated by
four different algorithms that produce structurally distinct trees.
"""

import random
import subprocess
import sys
from collections import Counter, defaultdict, deque


class Maze:
    """Perfect maze = spanning tree of the grid graph G_{rows,cols}."""

    def __init__(self, rows, cols):
        self.rows = rows
        self.cols = cols
        self.edges = set()  # {((r1,c1),(r2,c2))} with (r1,c1) < (r2,c2)

    def neighbors(self, r, c):
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = r + dr, c + dc
            if 0 <= nr < self.rows and 0 <= nc < self.cols:
                yield (nr, nc)

    def add_edge(self, u, v):
        self.edges.add((min(u, v), max(u, v)))

    def has_passage(self, u, v):
        return (min(u, v), max(u, v)) in self.edges

    def adjacency(self):
        adj = defaultdict(list)
        for u, v in self.edges:
            adj[u].append(v)
            adj[v].append(u)
        return adj

    def solve(self, start, end):
        adj = self.adjacency()
        parent = {start: None}
        queue = deque([start])
        while queue:
            node = queue.popleft()
            if node == end:
                path = []
                while node is not None:
                    path.append(node)
                    node = parent[node]
                return path[::-1]
            for nb in adj[node]:
                if nb not in parent:
                    parent[nb] = node
                    queue.append(nb)
        return []

    def degree_map(self):
        deg = defaultdict(int)
        for u, v in self.edges:
            deg[u] += 1
            deg[v] += 1
        return deg


# ---------------------------------------------------------------------------
# Generation algorithms
# ---------------------------------------------------------------------------

def gen_dfs(rows, cols):
    """Recursive backtracker — long winding corridors."""
    maze = Maze(rows, cols)
    visited = {(0, 0)}
    stack = [(0, 0)]
    while stack:
        r, c = stack[-1]
        nbs = [(nr, nc) for nr, nc in maze.neighbors(r, c) if (nr, nc) not in visited]
        if nbs:
            nr, nc = random.choice(nbs)
            maze.add_edge((r, c), (nr, nc))
            visited.add((nr, nc))
            stack.append((nr, nc))
        else:
            stack.pop()
    return maze


def gen_kruskal(rows, cols):
    """Randomized Kruskal's — short branchy passages."""
    maze = Maze(rows, cols)
    all_edges = []
    for r in range(rows):
        for c in range(cols):
            if c + 1 < cols:
                all_edges.append(((r, c), (r, c + 1)))
            if r + 1 < rows:
                all_edges.append(((r, c), (r + 1, c)))
    random.shuffle(all_edges)

    parent = {}
    rank = {}
    for r in range(rows):
        for c in range(cols):
            parent[(r, c)] = (r, c)
            rank[(r, c)] = 0

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        rx, ry = find(x), find(y)
        if rx == ry:
            return False
        if rank[rx] < rank[ry]:
            rx, ry = ry, rx
        parent[ry] = rx
        if rank[rx] == rank[ry]:
            rank[rx] += 1
        return True

    for u, v in all_edges:
        if union(u, v):
            maze.add_edge(u, v)
    return maze


def gen_wilson(rows, cols):
    """Wilson's algorithm — uniform random spanning tree."""
    maze = Maze(rows, cols)
    in_tree = {(0, 0)}
    cells = [(r, c) for r in range(rows) for c in range(cols)]

    for start in cells:
        if start in in_tree:
            continue
        path = [start]
        pos = {start: 0}
        cur = start
        while cur not in in_tree:
            nxt = random.choice(list(maze.neighbors(*cur)))
            if nxt in pos:
                idx = pos[nxt]
                for removed in path[idx + 1:]:
                    del pos[removed]
                path = path[:idx + 1]
                cur = nxt
            else:
                path.append(nxt)
                pos[nxt] = len(path) - 1
                cur = nxt
        for i in range(len(path) - 1):
            maze.add_edge(path[i], path[i + 1])
            in_tree.add(path[i])
        if path:
            in_tree.add(path[-1])
    return maze


def gen_prim(rows, cols):
    """Randomized Prim's — radiating growth."""
    maze = Maze(rows, cols)
    in_maze = {(0, 0)}
    frontier = []
    for nb in maze.neighbors(0, 0):
        frontier.append(((0, 0), nb))

    while frontier:
        idx = random.randrange(len(frontier))
        frontier[idx], frontier[-1] = frontier[-1], frontier[idx]
        u, v = frontier.pop()
        if v in in_maze:
            continue
        maze.add_edge(u, v)
        in_maze.add(v)
        for nb in maze.neighbors(*v):
            if nb not in in_maze:
                frontier.append((v, nb))
    return maze


# ---------------------------------------------------------------------------
# TikZ rendering
# ---------------------------------------------------------------------------

def maze_tikz(maze, cell=0.5, solution=True, tree_edges=False, label=None):
    """Render a maze as TikZ."""
    R, C = maze.rows, maze.cols
    lines = []
    lines.append(f"\\begin{{tikzpicture}}[x={cell}cm, y={cell}cm]")

    # Spanning tree edges (light blue behind walls)
    if tree_edges:
        lines.append("  % tree edges")
        for (r1, c1), (r2, c2) in maze.edges:
            x1, y1 = c1 + 0.5, R - r1 - 0.5
            x2, y2 = c2 + 0.5, R - r2 - 0.5
            lines.append(f"  \\draw[blue!25, line width=2.5pt] ({x1:.1f},{y1:.1f}) -- ({x2:.1f},{y2:.1f});")

    # Outer border with entry (top-left) and exit (bottom-right)
    lines.append("  % border")
    # Top
    lines.append(f"  \\draw[line width=1pt] (0,{R}) -- ({C},{R});")
    # Bottom
    lines.append(f"  \\draw[line width=1pt] (0,0) -- ({C},0);")
    # Left: gap at row 0 (top)
    lines.append(f"  \\draw[line width=1pt] (0,0) -- (0,{R - 1});")
    # Right: gap at row R-1 (bottom)
    lines.append(f"  \\draw[line width=1pt] ({C},1) -- ({C},{R});")

    # Entry/exit arrows
    lines.append(f"  \\draw[red!70!black, thick, ->, >=stealth] (-0.35,{R - 0.5:.1f}) -- (0.25,{R - 0.5:.1f});")
    lines.append(f"  \\draw[red!70!black, thick, ->, >=stealth] ({C - 0.25:.1f},0.5) -- ({C + 0.35:.1f},0.5);")

    # Internal horizontal walls (between row r and r+1)
    lines.append("  % internal walls")
    for r in range(R - 1):
        y = R - r - 1
        for c in range(C):
            if not maze.has_passage((r, c), (r + 1, c)):
                lines.append(f"  \\draw[line width=1pt] ({c},{y}) -- ({c + 1},{y});")

    # Internal vertical walls (between col c and c+1)
    for r in range(R):
        y = R - r
        for c in range(C - 1):
            if not maze.has_passage((r, c), (r, c + 1)):
                lines.append(f"  \\draw[line width=1pt] ({c + 1},{y}) -- ({c + 1},{y - 1});")

    # Solution path
    if solution:
        path = maze.solve((0, 0), (R - 1, C - 1))
        if path:
            lines.append("  % solution")
            coords = " -- ".join(f"({c + 0.5:.1f},{R - r - 0.5:.1f})" for r, c in path)
            lines.append(f"  \\draw[red!50!black, line width=0.8pt, opacity=0.5] {coords};")

    # Label
    if label:
        lines.append(f"  \\node[below] at ({C / 2:.1f},-0.3) {{\\footnotesize {label}}};")

    lines.append("\\end{tikzpicture}")
    return "\n".join(lines)


def stats_line(maze):
    """One-line LaTeX summary of tree statistics."""
    deg = maze.degree_map()
    dist = Counter(deg.values())
    n = maze.rows * maze.cols
    leaves = dist.get(1, 0)
    junctions = sum(v for k, v in dist.items() if k >= 3)
    path = maze.solve((0, 0), (maze.rows - 1, maze.cols - 1))
    sol_len = len(path) - 1 if path else 0
    shortest = maze.rows + maze.cols - 2
    tort = sol_len / shortest if shortest > 0 else 0
    deg_str = ", ".join(f"$d\\!=\\!{k}$:\\,{v}" for k, v in sorted(dist.items()))
    return (
        f"Leaves: {leaves} \\quad "
        f"Junctions: {junctions} \\quad "
        f"Solution: {sol_len} steps \\quad "
        f"Tortuosity: {tort:.2f}\\\\\n"
        f"Degree distribution: {deg_str}"
    )


def generate_document(size=8, seed=42):
    algorithms = [
        ("DFS", gen_dfs),
        ("Kruskal", gen_kruskal),
        ("Wilson", gen_wilson),
        ("Prim", gen_prim),
    ]

    cell = 0.7

    doc = []
    doc.append(r"""\documentclass[border=5mm]{standalone}
\usepackage{tikz}
\usepackage[T1]{fontenc}
\usepackage{lmodern}

\begin{document}
\begin{tikzpicture}
""")

    spacing = size * cell + 2.0  # horizontal gap between mazes

    for i, (name, gen_func) in enumerate(algorithms):
        random.seed(seed + i)
        maze = gen_func(size, size)
        xoff = i * spacing

        doc.append(f"  \\begin{{scope}}[shift={{({xoff:.1f},0)}}]")
        # Maze walls
        R, C = maze.rows, maze.cols
        # Outer border
        doc.append(f"    \\draw[line width=1pt] (0,{R*cell}) -- ({C*cell},{R*cell});")
        doc.append(f"    \\draw[line width=1pt] (0,0) -- ({C*cell},0);")
        doc.append(f"    \\draw[line width=1pt] (0,0) -- (0,{(R-1)*cell});")
        doc.append(f"    \\draw[line width=1pt] ({C*cell},{cell}) -- ({C*cell},{R*cell});")
        # Entry/exit arrows
        doc.append(f"    \\draw[red!70!black, thick, ->, >=stealth] (-0.25,{(R-0.5)*cell:.2f}) -- (0.2,{(R-0.5)*cell:.2f});")
        doc.append(f"    \\draw[red!70!black, thick, ->, >=stealth] ({(C-0.3)*cell:.2f},{0.5*cell:.2f}) -- ({C*cell+0.25:.2f},{0.5*cell:.2f});")
        # Internal walls
        for r in range(R - 1):
            y = (R - r - 1) * cell
            for c in range(C):
                if not maze.has_passage((r, c), (r + 1, c)):
                    doc.append(f"    \\draw[line width=1pt] ({c*cell},{y}) -- ({(c+1)*cell},{y});")
        for r in range(R):
            y_top = (R - r) * cell
            y_bot = (R - r - 1) * cell
            for c in range(C - 1):
                if not maze.has_passage((r, c), (r, c + 1)):
                    doc.append(f"    \\draw[line width=1pt] ({(c+1)*cell},{y_top}) -- ({(c+1)*cell},{y_bot});")
        # Solution path
        path = maze.solve((0, 0), (R - 1, C - 1))
        if path:
            coords = " -- ".join(f"({(c+0.5)*cell:.2f},{(R-r-0.5)*cell:.2f})" for r, c in path)
            doc.append(f"    \\draw[red!50!black, line width=0.7pt, opacity=0.45] {coords};")
        # Label
        doc.append(f"    \\node[below, font=\\small\\bfseries] at ({C*cell/2:.2f},-0.3) {{{name}}};")
        doc.append(f"  \\end{{scope}}")
        doc.append("")

    doc.append(r"\end{tikzpicture}")
    doc.append(r"\end{document}")
    return "\n".join(doc)


if __name__ == "__main__":
    size = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else 42

    latex = generate_document(size=size, seed=seed)
    tex_path = "mazes.tex"
    with open(tex_path, "w") as f:
        f.write(latex)
    print(f"Written {tex_path}")

    result = subprocess.run(
        ["pdflatex", "-interaction=nonstopmode", tex_path],
        capture_output=True, text=True
    )
    if result.returncode == 0:
        print("Compiled mazes.pdf")
    else:
        print("pdflatex failed:")
        print(result.stdout[-2000:])
        sys.exit(1)
